### ISSUE TITLE
[功能介绍] Umi App 数据采集和通讯

### ISSUE THREAD

**Issue by chiaweilee** [umijs/Mongchhi#16]
## 采集时机

支持的时机：
- [x] mongchhi 启动时采集
- [x] 新 App 启动时（有 Mongchhi 插件的）
- [ ] 检测到新 App 时，socket 通知 UI 刷新
- [ ] UI 手动刷新 App 列表
- [ ] UI 手动添加项目

## 采集到 AppData 写入缓存文件

- [x] 缓存服务

MAC: `/Users/admin/.mongchhi/.cache`
WIN: `C:\Users\admin\.mongchhi/.cache`

## UI 获取 AppData

- [x] 通过 Socket 获取 AppData

**Comment by xiaohuoni** [comment]
> 通过 Socket 即时同步 AppData？
看看这里是不是能用
https://github.com/umijs/Mongchhi/pull/19
